// Auto-generated station ID mappings
// Generated by scripts/add_station.py - DO NOT EDIT MANUALLY

window.stationIdMap = {
    '1a3e62c7': '1a3e62c7-b554-4b05-817d-de2c1efc048a',
    '1ee05a4a': '1ee05a4a-55c2-4ca0-95c6-7616d6d0d87e',
    '1f8b883f': '1f8b883f-e7fd-4645-89cd-d1beb4dc86f3',
    '4ff73031': '4ff73031-0203-4016-b5d5-158c411842d6',
    '52431c32': '52431c32-0b35-426e-a47c-cdf7172f7b8a',
    '6a959157': '6a959157-6ddc-4005-b3e5-0da4864806f7',
    '6d8bc05a': '6d8bc05a-4a50-4f61-beb8-dae2a742ea93',
    'c5022a04': 'c5022a04-4077-4fe5-8eb1-7b7e395b5bf9',
};

// Station management class
class StationMap {
    constructor() {
        this.stationsCache = null;
    }

    /**
     * Get all stations with their names
     */
    async getStations() {
        if (this.stationsCache) {
            return this.stationsCache;
        }

        const stations = [];

        try {
            // Load stations.json to get the correct order
            const response = await fetch('data/stations.json');
            if (!response.ok) {
                throw new Error('stations.json not found');
            }

            const manifest = await response.json();
            const stationIds = manifest.stations || [];

            // Load station configs in the order from stations.json
            for (const fullId of stationIds) {
                const shortId = fullId.substring(0, 8);

                try {
                    const configResponse = await fetch(`data/${fullId}/station_config.yaml`);
                    if (configResponse.ok) {
                        const yamlText = await configResponse.text();
                        const config = jsyaml.load(yamlText);
                        stations.push({
                            id: shortId,
                            fullId: fullId,
                            name: config.station_name || `Station ${shortId}`
                        });
                    }
                } catch (error) {
                    console.error(`Error loading station ${shortId}:`, error);
                    stations.push({
                        id: shortId,
                        fullId: fullId,
                        name: `Station ${shortId}`
                    });
                }
            }
        } catch (error) {
            console.error('Error loading stations.json:', error);
            // Fallback to using stationIdMap if stations.json fails
            for (const [shortId, fullId] of Object.entries(window.stationIdMap)) {
                stations.push({
                    id: shortId,
                    fullId: fullId,
                    name: `Station ${shortId}`
                });
            }
        }

        this.stationsCache = stations;
        return stations;
    }

    /**
     * Get full ID from short ID
     */
    getFullId(shortId) {
        return window.stationIdMap[shortId] || null;
    }
}

// Create global instance
window.stationMap = new StationMap();
