#!/usr/bin/env python3
"""
Station Viewer - Auto Station Discovery and Registration
This script automatically discovers and registers new station data.

Usage:
    python scripts/add_station.py

This will:
1. Search for all unregistered stations and add them to stations.json and station-map.js
2. Search for all stations without agent indices and initialize them
3. Update index.html to include station-map.js if needed
"""

import os
import json
import yaml
from pathlib import Path
from init_agent import init_agent_index, check_agent_index_exists
from init_archive import init_archive_index, check_archive_index_exists
from init_memory import init_public_memory, init_private_memory
from init_mail import init_mail_index
from init_research import init_research_index


def get_station_info(station_path):
    """Get station name and other info from station_config.yaml"""
    config_path = os.path.join(station_path, 'station_config.yaml')
    if os.path.exists(config_path):
        try:
            with open(config_path, 'r') as f:
                config = yaml.safe_load(f)
                return {
                    'name': config.get('station_name', 'Unknown Station'),
                    'tick': config.get('current_tick', 0),
                    'status': config.get('status', 'Unknown')
                }
        except Exception as e:
            print(f"  Warning: Could not read config for {station_path}: {e}")
    return {'name': 'Unknown Station', 'tick': 0, 'status': 'Unknown'}


def discover_all_stations(data_dir):
    """Discover all station folders (UUID-like folder names)"""
    stations = []
    station_map = {}

    for folder in os.listdir(data_dir):
        folder_path = os.path.join(data_dir, folder)
        # Check if it's a directory with UUID format
        if os.path.isdir(folder_path) and len(folder) >= 36 and folder.count('-') == 4:
            stations.append(folder)
            short_id = folder[:8]
            station_map[short_id] = folder

    return sorted(stations), station_map


def load_existing_stations(data_dir):
    """Load existing station registrations from stations.json"""
    stations_file = os.path.join(data_dir, 'stations.json')
    if os.path.exists(stations_file):
        try:
            with open(stations_file, 'r') as f:
                data = json.load(f)
                return set(data.get('stations', []))
        except Exception as e:
            print(f"Warning: Could not read stations.json: {e}")
    return set()


def load_existing_station_map(viewer_dir):
    """Load existing station map from station-map.js"""
    js_file = os.path.join(viewer_dir, 'js', 'station-map.js')
    if os.path.exists(js_file):
        try:
            with open(js_file, 'r') as f:
                content = f.read()
                # Extract mappings from JavaScript
                import re
                pattern = r"'([^']+)':\s*'([^']+)'"
                matches = re.findall(pattern, content)
                return {short: full for short, full in matches}
        except Exception as e:
            print(f"Warning: Could not read station-map.js: {e}")
    return {}


def update_stations_json(data_dir, stations):
    """Update stations.json with all registered stations"""
    stations_file = os.path.join(data_dir, 'stations.json')
    with open(stations_file, 'w') as f:
        json.dump({'stations': sorted(list(stations))}, f, indent=2)


def update_station_map_js(viewer_dir, station_map):
    """Update station-map.js with all station ID mappings"""
    js_content = """// Auto-generated station ID mappings
// Generated by scripts/add_station.py - DO NOT EDIT MANUALLY

window.stationIdMap = {
"""

    for short_id, full_id in sorted(station_map.items()):
        js_content += f"    '{short_id}': '{full_id}',\n"

    js_content += "};\n"

    js_file = os.path.join(viewer_dir, 'js', 'station-map.js')
    with open(js_file, 'w') as f:
        f.write(js_content)


def ensure_station_map_in_html(viewer_dir):
    """Ensure station-map.js is included in index.html"""
    index_path = os.path.join(viewer_dir, 'index.html')
    with open(index_path, 'r') as f:
        content = f.read()

    # Check if station-map.js is already included
    if 'station-map.js' not in content:
        # Add it after router.js
        content = content.replace(
            '<script src="js/router.js"></script>',
            '<script src="js/router.js"></script>\n    <script src="js/station-map.js"></script>'
        )
        with open(index_path, 'w') as f:
            f.write(content)
        return True
    return False


def main():
    """Main function to manage station registration and initialization"""
    # Get directories
    script_dir = os.path.dirname(os.path.abspath(__file__))
    viewer_dir = os.path.dirname(script_dir)
    data_dir = os.path.join(viewer_dir, 'data')

    # Create data directory if it doesn't exist
    if not os.path.exists(data_dir):
        os.makedirs(data_dir)

    print("=================================================")
    print("Station Viewer - Auto Station Discovery")
    print("=================================================")
    print()
    print(f"Scanning for stations in: {data_dir}")
    print()

    # Discover all stations
    all_stations, all_station_map = discover_all_stations(data_dir)

    if not all_stations:
        print("No station directories found in", data_dir)
        print()
        print("Station directories should be UUID format:")
        print("  Example: c5022a04-4077-4fe5-8eb1-7b7e395b5bf9")
        print()
        print("To add a station:")
        print(f"  1. Copy your station_data folder to: {data_dir}/{{station-uuid}}/")
        print("  2. Run this script again")
        return

    # Load existing registrations
    registered_stations = load_existing_stations(data_dir)
    existing_map = load_existing_station_map(viewer_dir)

    # Find unregistered stations
    unregistered = set(all_stations) - registered_stations
    new_mappings = {k: v for k, v in all_station_map.items() if k not in existing_map}

    # Count stations needing agent indices
    need_agent_indices = []
    for station_id in all_stations:
        station_path = os.path.join(data_dir, station_id)
        if not check_agent_index_exists(station_path):
            need_agent_indices.append(station_id)

    # Count stations needing archive indices
    need_archive_indices = []
    for station_id in all_stations:
        station_path = os.path.join(data_dir, station_id)
        if not check_archive_index_exists(station_path):
            need_archive_indices.append(station_id)

    # Count stations needing memory indices
    need_memory_indices = []
    for station_id in all_stations:
        station_path = os.path.join(data_dir, station_id)
        public_path = os.path.join(station_path, 'capsules', 'public', '_index.json')
        private_path = os.path.join(station_path, 'capsules', 'private', '_index.json')
        # Check if either public or private index is missing
        if not (os.path.exists(public_path) and os.path.exists(private_path)):
            need_memory_indices.append(station_id)

    # Count stations needing mail indices
    need_mail_indices = []
    for station_id in all_stations:
        station_path = os.path.join(data_dir, station_id)
        mail_index_path = os.path.join(station_path, 'capsules', 'mail', '_index.json')
        if not os.path.exists(mail_index_path):
            need_mail_indices.append(station_id)

    # Count stations needing research indices
    need_research_indices = []
    for station_id in all_stations:
        station_path = os.path.join(data_dir, station_id)
        research_index_path = os.path.join(station_path, 'evaluations', '_index.json')
        if not os.path.exists(research_index_path):
            need_research_indices.append(station_id)

    print(f"Found {len(all_stations)} station(s):")
    print(f"  • {len(registered_stations)} already registered")
    print(f"  • {len(unregistered)} new stations to register")
    print(f"  • {len(need_agent_indices)} stations need agent indices")
    print(f"  • {len(need_archive_indices)} stations need archive indices")
    print(f"  • {len(need_memory_indices)} stations need memory indices")
    print(f"  • {len(need_mail_indices)} stations need mail indices")
    print(f"  • {len(need_research_indices)} stations need research indices")
    print()

    # Register new stations
    if unregistered:
        print("Registering new stations:")
        for station_id in sorted(unregistered):
            station_path = os.path.join(data_dir, station_id)
            info = get_station_info(station_path)
            print(f"  ✓ {station_id[:8]}: {info['name']}")

        # Update registrations
        all_registered = registered_stations.union(unregistered)
        update_stations_json(data_dir, all_registered)
        update_station_map_js(viewer_dir, all_station_map)
        print(f"  Updated stations.json and station-map.js")
        print()

    # Initialize agent indices for stations that need them
    if need_agent_indices:
        print("Initializing agent indices:")
        for station_id in need_agent_indices:
            station_path = os.path.join(data_dir, station_id)
            agents = init_agent_index(station_path)
            info = get_station_info(station_path)
            print(f"  ✓ {station_id[:8]}: {info['name']} ({len(agents)} agents)")
        print()

    # Initialize archive indices for stations that need them
    if need_archive_indices:
        print("Initializing archive indices:")
        for station_id in need_archive_indices:
            station_path = os.path.join(data_dir, station_id)
            archives = init_archive_index(station_path)
            if archives:
                info = get_station_info(station_path)
                print(f"  ✓ {station_id[:8]}: {info['name']} ({len(archives)} archives)")
        print()

    # Initialize memory indices for stations that need them
    if need_memory_indices:
        print("Initializing memory capsule indices:")
        for station_id in need_memory_indices:
            station_path = os.path.join(data_dir, station_id)
            public_memories = init_public_memory(station_path)
            private_lineages = init_private_memory(station_path)
            info = get_station_info(station_path)
            total_private = sum(len(mems) for mems in private_lineages.values()) if private_lineages else 0
            print(f"  ✓ {station_id[:8]}: {info['name']} ({len(public_memories)} public, {total_private} private)")
        print()

    # Initialize mail indices for stations that need them
    if need_mail_indices:
        print("Initializing mail indices:")
        for station_id in need_mail_indices:
            station_path = os.path.join(data_dir, station_id)
            mails = init_mail_index(station_path)
            if mails:
                info = get_station_info(station_path)
                print(f"  ✓ {station_id[:8]}: {info['name']} ({len(mails)} mail threads)")
        print()

    # Initialize research indices for stations that need them
    if need_research_indices:
        print("Initializing research indices:")
        for station_id in need_research_indices:
            station_path = os.path.join(data_dir, station_id)
            evaluations = init_research_index(station_path)
            if evaluations:
                info = get_station_info(station_path)
                breakthroughs = sum(1 for e in evaluations if e['breakthrough'])
                print(f"  ✓ {station_id[:8]}: {info['name']} ({len(evaluations)} evaluations, {breakthroughs} breakthroughs)")
        print()

    # Ensure station-map.js is in HTML
    if ensure_station_map_in_html(viewer_dir):
        print("Updated index.html to include station-map.js")
        print()

    # Summary
    print("=================================================")

    if unregistered or need_agent_indices or need_archive_indices or need_memory_indices or need_mail_indices or need_research_indices:
        print("✅ Station registration complete!")
        print()
        print(f"  • Registered {len(unregistered)} new station(s)")
        print(f"  • Initialized {len(need_agent_indices)} agent indices")
        print(f"  • Initialized {len(need_archive_indices)} archive indices")
        print(f"  • Initialized {len(need_memory_indices)} memory indices")
        print(f"  • Initialized {len(need_mail_indices)} mail indices")
        print(f"  • Initialized {len(need_research_indices)} research indices")
    else:
        print("✅ All stations already registered and indexed!")

    print()
    print("Next steps:")
    print("  1. Open viewer/index.html in your browser")
    print("  2. All stations should now be visible")
    print("  3. No server restart needed - just refresh!")
    print()
    print("To add more stations in the future:")
    print(f"  1. Copy station data to: {data_dir}/{{station-uuid}}/")
    print("  2. Run: python scripts/add_station.py")
    print("=================================================")


if __name__ == '__main__':
    # Check if PyYAML is installed
    try:
        import yaml
    except ImportError:
        print("Error: PyYAML is required but not installed")
        print("Please install it with: pip install pyyaml")
        exit(1)

    main()